### ISSUE TITLE
Notification 관련, 엔티티 삭제 시 연관관계 문제

### ISSUE THREAD

**Issue by melonturtle** [team-offonoff/server#176]
현재 토픽 생성 후 `VoteResultNotifiaction`가 생성된 후에 토픽 엔티티를 삭제하려고 하면, Notification이 VoteResult를 참조하고 있어서 VoteResult를 삭제하지 못해서, Topic을 삭제하지 못하는 문제가 있습니다.

![image](https://github.com/team-offonoff/server/assets/101321313/3581c696-d181-4813-a03f-96a5bccda142)

위 사진처럼 VoteResultNotifiacation의 VoteResult 필드에 On delete cascade를 걸어주면 삭제가 되긴 하는데, (DDL에서 걸리는 옵션이라 테이블 수동으로 수정해야함) 제가 Notification 쪽을 확실히 아는게 아니라 이런 비슷한 문제가 있으면 그거랑 같이 해결해주시면 좋을 것 같아요!

**Comment by 60jong** [comment]
넵 해결하도록 하겠습니다~

**Comment by 60jong** [comment]
일단 토픽 삭제되면 관련된 알람도 모두 삭제해버릴게요
