### ISSUE TITLE
Stream에서의 Repository 조회 문제

### ISSUE THREAD

**Issue by melonturtle** [team-offonoff/server#180]
@60jong 

서버 로그를 살펴보다가, 토픽 조회 한 번인데도 멤버가 여러번 조회되는 문제를 확인했습니다.

![스크린샷 2024-02-26 오후 8 02 59](https://github.com/team-offonoff/server/assets/101321313/1716786d-3811-4897-8625-febc3e4a4073)

확인해보니까, 현재 `TopicService`에서 토픽 조회 후 토픽마다 Response 모델로 변환하는 과정에서 계속 `findMember`를 호출해서 멤버를 조회하는데, 이 과정에서 계속 새로운 query로 멤버를 조회하는 걸 확인했습니다.

```java
public Slice<TopicResponse> findAll(final Long memberId, final TopicSearchRequest request, final Pageable pageable) {

    Slice<Topic> topics = topicRepository.findAll(memberId, request, pageable);

    if (memberId == null) {
        return topics.map(TopicResponse::from);
    }

    // 여기
    return topics.map(topic -> TopicResponse.from(topic, findMember(memberId)));
}
```

그래서 memberId는 topic과 달리 어차피 stream에서 변하지 않으니까, Member를 한 번만 찾는 걸로 수정 후에 쿼리가 여러번 전송되지 않는 걸 확인했습니다.

```java
Member member = findMember(memberId);
return topics.map(topic -> TopicResponse.from(topic, member));
```

간단하니까 바로 PR 올릴 건데, stream 사용할 때 한 줄이어도 loop문이라는 걸 한 번 상기하고 넘어가면 좋을 것 같아 이슈로 남깁니당. 저도 이런 실수한 게 있을 수도.. 있으면 수정해주세요!

**Comment by 60jong** [comment]
그런 점을 잊고 있었네요ㅜㅜ 감사합니다!! 보일때마다 수정 pr올릴게요!
