### ISSUE TITLE
`VoteResult` 엔티티 역할 관련

### ISSUE THREAD

**Issue by melonturtle** [team-offonoff/server#185]
코드를 살펴보다보니까, `VoteResult`가 엔티티로 저장되어야하는 이유가 애매해서 궁금해서 물어볼려구용.

- VoteResult가 Topic에도 저장되는 것 같던데, 만약 VoteResult가 존재하면 투표가 끝났음을 의미하는 걸로 보기엔 대신 Topic에 `status`가 있어서 CLOSED를 거기서 표시해주는 것 같아 이 역할은 아닌 것 같음
- 투표 종료 이벤트 발생시에 VoteResult를 전송하는걸로 알고 있는데, VoteResult가 엔티티가 아니라 그냥 일반 객체였어도 이벤트에는 문제가 없어 보임
- Notification에 VoteResult를 저장하는데, 어차피 클라이언트에서 알림을 누르면 토픽으로 이동될거니까 필요하다면 Topic id만 있어도됨
- 또 Notification에 totalVoteCount가 있어서 VoteResult에 있는 totalVoteCount가 필요 없어 보임 → VoteResult에서 totalVoteCount가 없으면 topicId밖에 없으니까 topicId만 있는 것과 같음

위 이유로 굳이 엔티티일 필요 없이 그냥 dto여도 될 것 같은데, 엔티티로 저장하는 이유가 있나요?

**Comment by 60jong** [comment]
예전에 Topic에 votecount같은 누적 결과 필드 만들기 전에 투표 결과가 필요해 만들었었는데 이제 튜표 결과 관련된 필드들이 많이 생겨서 VoteResult 엔티티의 존재의미가 없어지긴 했네요

**Comment by 60jong** [comment]
삭제해보도록 할게요~~

**Comment by melonturtle** [comment]
아항 그렇군요 감사합니다~~
